# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.CharField(choices=[(b'vegetable', b'Vegetable'), (b'fruit', b'Fruit')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('deceased', models.BooleanField(default=False)),
                ('eye_color', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.Company')),
                ('favourite_foods', models.ManyToManyField(blank=True, to='api.FoodItem')),
                ('friends', models.ManyToManyField(blank=True, to='api.Person')),
            ],
        ),
    ]
